services:
  gateway:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "6433:6433"
      # - "5052:6433"
      # - "6433:5052"
      # - "5052:5052"
  redis:
    image: "redis"
    # ports:
    #   - "6379:6379"
